### ISSUE TITLE
Incorrect scale line - incorrect distance value

### ISSUE THREAD

**Issue by xintrea** [OpenSeaMap/online_chart#101]
Hi!

Your scale line (at corner of map) is incorrect.

See at this image: [OSM vs OSeaM](http://i.piccy.info/i9/0f8fbf1a578372dd84b19ed5b52a6a66/1541103783/79491/1279414/osm_vs_oseam.png)

Real distance of 1km your engine show as 1nmi. And your 1 km is too small relatively real 1km.

I compared OpenSeaMap scale line with OpenStreetMap, YandexMaps, GoogleMaps. All this map service show correct distance. But OpenSeaMap show incorrect.

Please, fix it.

**Comment by Nautic** [comment]
Hi, thanks for your error message.
Please can you add a permalink for the OpenSeaMap ann OpenStreetMap position?
Thanks, Markus

**Comment by xintrea** [comment]
If put locality at center of browser windows:

OpenStreetMap: https://www.openstreetmap.org/#map=12/59.9955/29.7513

OpenSeaMap: http://map.openseamap.org/?zoom=13&lat=59.99936&lon=29.73647&layers=BFTFFFFFFTF0TFFFFFFFFF

**Comment by mojoaxel** [comment]
Looks like the distance-indicator is off by one zoom-level in OpenSeaMap.

**Comment by wschildbach** [comment]
I think it is off by more -- if you put both an OpenStreetMap and an OpenSeaMap display at equal scale, the ScaleLine has a different size not a factor of two.
The OpenLayers ScaleLine module has seen a number of bug fixes relating to scale. We should consider updating to a newer version of openLayers.

**Comment by Nautic** [comment]
Mit gleichem Zoomlevel und gleichem Kartenmittelpunkt 
sind die Kartenausschnitte in OSM (OL ?) und OpenSeaMap (OL 2) identisch.
Aber die Skalen zeigen in OSM 500m, in OpenSeaMap 1km,
und die Skalenlänge differiert von OSM mit 12mm für 500m zu OpenSeaMap mit 13,5mm für 1km.

Ich vermute den Fehler im Skript für den Massstab (scale).
Siehe #17

Update auf [OL-6](https://openlayers.org/download/) wäre sinnvoll - aber ein anderer Issue.
Zum geplanten OL-3-Update (2013) siehe Issues [OL-3](https://github.com/OpenSeaMap/online_chart/issues?q=is%3Aissue+is%3Aopen+label%3Aopenlayers3)

**Comment by wschildbach** [comment]
With an additional patch (PR forthcoming), this is what the ScaleLine looks like:

![image](https://user-images.githubusercontent.com/4427008/66546203-ce1bbc00-eb3c-11e9-9efa-61b0fbd52fe2.png)

**Comment by wschildbach** [comment]
Hi @xintrea , can you take another look whether the problem is resolved and close the bug if it is?

**Comment by Nautic** [comment]
Vielen Dank für die Korrektur, und für die Verbesserung im Layout :-)
In z=14,15,17,18 finde ich das Layout hilfreich.

In z=3..11 könnte die Linie deutlich länger sein (Faktor 5?)
In z=12,13,16 könnte die Linie noch länger sein (Faktor 2..3?)
In z=15 ist das Verhältnis von nmi und km noch ungünstig (nmi grösser)

**Comment by wschildbach** [comment]
moved last comment into new feature #132 and closing this one.
