### ISSUE TITLE
dumping_ground is not rendered

### ISSUE THREAD

**Issue by adrien-github** [OpenSeaMap/online_chart#102]
Hi,
It seems that dumping ground are not rendered on OpenSeaMap. For instance I've map one with explosives along the french coast, but it doesn't appears :
https://map.openseamap.org/?zoom=14&lat=47.32772&lon=-2.53526&layers=BFTTFTTFFTF0TFFFFFFFFT
https://www.openstreetmap.org/way/638556381#map=14/47.3230/-2.5384&layers=D

Do you think it would be possible to rendered it ?

Kind regards,

Adrien

**Comment by mojoaxel** [comment]
@aAXEe maybe this could be implementented in https://github.com/aAXEe/online_chart_ol3 !?

**Comment by Dirk--** [comment]
@malcolmh  does the seamark rendering

**Comment by malcolmh** [comment]
fixed

**Comment by malcolmh** [comment]
As there were only 14 such areas, I touched them all to force a re-render. Should be visible now.
