### ISSUE TITLE
Harbour mapped as multipolygon doesn't appears on openseamap

### ISSUE THREAD

**Issue by adrien-github** [OpenSeaMap/online_chart#103]
Hi,
The harbour “Port de la Meule” on the island of Yeu (French Atlantic coast) is mapped as a multipolygon in OpenStreetMap:
https://www.openstreetmap.org/relation/2063793#map=17/46.69440/-2.34521

Despite having the right seamark tags, it didn't appears on OpenSeaMap:
https://map.openseamap.org/?zoom=16&lat=46.69392&lon=-2.34681&layers=BFTTFTTFFTF0TFFFFFFFFF

Kind regards,

Adrien

**Comment by Dirk--** [comment]
@malcolmh might answer this

**Comment by malcolmh** [comment]
OK, it is time to get my new renderer into service! The existing one does not process mutipolygons, but the new one does. I have just done a test rendering of the area in question to check that claim.

I have ordered a new (faster!) machine that will be able to do both the rendering & run the Overpass server - currently these tasks are on two different machines. I will run both renderers in parallel for a time whilst I do the final debugging. Hopefully this will be complete by the end of March.

**Comment by stevo01** [comment]
> The existing one does not process mutipolygons, but the new one does.

Hi Malcolm,
is this feature integrated to "https://svn.openstreetmap.org/applications/editors/josm/plugins/seachart/jrender/" yet?

**Comment by malcolmh** [comment]
Yes. The only restriction is the ways with role=outer must form a single ring. No disjunct outers!

**Comment by wschildbach** [comment]
@malcolmh sounds like this is deployed -- can we close the bug?

**Comment by malcolmh** [comment]
Yes
