### ISSUE TITLE
Sea are names are rendered too big for size, overlaying chart details

### ISSUE THREAD

**Issue by Krillle** [OpenSeaMap/online_chart#108]
The names of sea areas like bays or shoals are rendered in a too big font size, which leads to cluttered map if several areas are close together.

**Comment by wschildbach** [comment]
Hi @Krille, can you give a permalink so I can easily repro this issue? Thanks!

**Comment by Nautic** [comment]
Hier ein Beispiel in Mallorca:
https://map.openseamap.org/?zoom=12&lat=39.3575&lon=3.23155&layers=BFTFFFTFFTF0FFFFFFFFFF

**Comment by malcolmh** [comment]
Fixed
