### ISSUE TITLE
Harbours not displaying

### ISSUE THREAD

**Issue by wkmhv** [OpenSeaMap/online_chart#122]
http://dev.openseamap.org/website/map/api/getHarbours.php?b=43.16098&t=43.46375&l=16.23863&r=17.39219&ucid=0&maxSize=5&zoom=11

This link return 404
Any idea what's wrong?

**Comment by wschildbach** [comment]
Yes, this is a known issue -- harbour display is broken currently, unfortunately. We are working on it but it might be a little while...

**Comment by wkmhv** [comment]
according this page. https://github.com/OpenSeaMap/online_chart/blob/master/dependencies.md
it should return something like this:
putHarbourMarker(1226, 16.396666666667, 43.163333333333, 'Sv._Klement - Marina PalmiÅ¾ana', 'http://www.skipperguide.de/wiki/Sv._Klement#Marina_Palmi.C5.BEana', '5');
But now I got a php file.

**Comment by wschildbach** [comment]
One #133 is deployed, this will be fixed.
