### ISSUE TITLE
Error message when JavaScript is deactivated

### ISSUE THREAD

**Issue by dfa** [OpenSeaMap/online_chart#13]
When JavaScript is deactivated, the map will not be displayed. An error message like on OpenStreetMap can be a solution.
#### Acceptance criteria
- An error message is displayed when JavaScript is disabled.
- No error message is displayed when JavaScript is enabled.
#### Migrated from SourceForge

ID: 2839024
Submitted: Markus - 2009-08-17 07:41:49 PDT
Details:

Wenn auf dem PC kein Javascript installiert ist, erscheint die Website ohne Karte.
Hier wäre eine Fehlermeldung erforderlich (wie bei OSM)

**Comment by ehrenfeu** [comment]
This still applies to the OpenLayers3 implementation and should be addressed there as well.
