### ISSUE TITLE
SSL: openseamap.org tries to load javascript via HTTP

### ISSUE THREAD

**Issue by runette** [OpenSeaMap/online_chart#142]
The current servers for OpenSeaMap only seem to serve HTTP - which nowadays makes it impossible to integrate it into any site using https.

All sites these days should be using https. Is there anyway or plans to get the earmarks available on https?

**Comment by Nautic** [comment]
For which site do you want to use OpenSeaMap?
https://map.openseamap.org/ works fine, the integration in https://openseamap.org too.

**Comment by Dirk--** [comment]
Tile server supports https, too:
https://t2.openseamap.org/tile/6/34/20.png

**Comment by runette** [comment]
Thanks - I think I was trying t1 and not getting a response

**Comment by runette** [comment]
BTW - "not for nothing" (a curious but useful English phrase) but just so as you know ...

> https://map.openseamap.org/ works fine,

Actually - no it doesn't. Certainly, on my Chrome browser it reports as "Not Secure" because of mixed content and they are all starting to get much stricter about that. 

As a case in point :

> the integration in https://openseamap.org too. 

Actually - no it doesn't. Again in my Chrome Browser the map does NOT show when accessed using https. This is because of mixed content and the page works in HTTP!

**Comment by smurfix** [comment]
While that's correct, you initially wrote

> The current servers for OpenSeaMap only seem to serve HTTP

which is quite obviously not correct.

It would have been a lot more helpful if you had actually looked at the traffic and told us *which* content it fetches via HTTP-no-S, instead of expecting us to do that, esp. since it's entirely possible that depending on personal settings the problem doesn't always show up.

TBH: It's loading tiles from http://t1.openseamap.org.

**Comment by smurfix** [comment]
Also (and worse), openseamap.org tries to load OpenLayers.js and OpenStreetMap.js without SSL. Current Firefox already blocks that, making the page somewhat unuseable.

**Comment by runette** [comment]
To be completely correct, I am not trying to get map.openseamap.org to do anything - I am adding the seamarks as an overlay to another map in OpenLayers. That was probably slightly lost since my spell checker keeps changing "seamarks" to "earmarks"! {and I am English and I have no idea what an "earmark" would be!}.

All of the documentation (e.g. http://wiki.openseamap.org/wiki/OpenSeaMap_in_Website) and the actual site retro-engineered all access this using HTTP. This Dirk's response solved the problem - although I thought I had tried that. I must have had a typo.

The additional comment was intended to be helpful - those sites are not working correctly. Depending on which browser you are using one or both sites is broken because of mixed content and the situation will only get worse. This is not intended to be a criticism, but if you think they are working then you need to know that they are not.

**Comment by smurfix** [comment]
We still have HTTP content on an HTTPS site, which means that https://openseamap.org/ doesn't show a chart on recent Firefox et al.

**Comment by stevo01** [comment]
> We still have HTTP content on an HTTPS site, which means that https://openseamap.org/ doesn't show a chart on recent Firefox et al.
> Thus I'm re-opening this.

For me it seems to be a issue for https://github.com/OpenSeaMap/website instead of  of project https://github.com/OpenSeaMap/online_chart/.

**Comment by smurfix** [comment]
Right … I was confused. sorry. Closing.

**Comment by stevo01** [comment]
I added javascript files for openlayers to directory "/var/www/openseamap/typo3/js" and made update in file ./typo3/fileadmin/template/resources/addhead/addhead_start.txt.
