### ISSUE TITLE
the wikipedia layer does not work

### ISSUE THREAD

**Issue by stevo01** [OpenSeaMap/online_chart#143]
sample: 
https://map.openseamap.org/?zoom=10&lat=49.48953&lon=11.22642&layers=BFTFFFTFFTT0FFFFFFFFFF

**Comment by stevo01** [comment]
api/proxy-wikipedia.php seems to be responsible to fetch data from https://tools.wmflabs.org/

a manual call of "https://map.openseamap.org/api/proxy-wikipedia.php" shows 
![image](https://user-images.githubusercontent.com/33812539/89255961-5961c300-d623-11ea-8b04-ce9378962ed0.png)

**Comment by stevo01** [comment]
analysis in webbrowser shows that url "https://tools.wmflabs.org/wp-world/marks.php" is redirected to "https://wp-world.toolforge.org/marks.php "

the following patch solves the problem:
```
diff --git a/api/proxy-wikipedia.php b/api/proxy-wikipedia.php
index e99eae5..487ac52 100644
--- a/api/proxy-wikipedia.php
+++ b/api/proxy-wikipedia.php
@@ -2,11 +2,11 @@
 // PHP Proxy for map.openseamap.org to reach the wmflabs tool server
 
 // Allowed hostname (api.local and api.travel are also possible here)
-define ('HOSTNAME', 'https://tools.wmflabs.org/');
+define ('HOSTNAME', 'https://wp-world.toolforge.org/');
 
 // Get the REST call path from the AJAX application
 // Is it a POST or a GET?
-$path = "wp-world/marks.php?LANG=".htmlspecialchars($_GET["LANG"]) .
+$path = "marks.php?LANG=".htmlspecialchars($_GET["LANG"]) .
     "&thumbs=".htmlspecialchars($_GET["thumbs"]) .
         "&bbox=".htmlspecialchars($_GET["bbox"]) ;`
```

**Comment by aAXEe** [comment]
Thanks a lot @stevo01.

> Proposal: make the php code more robust and follow redirections ...

Of course a good idea but do we realy (still) need this proxy script? 
With modern javascript we should do the request directly from the users browser and get data directly. CORS needs to be configured properly at the destination server to allow this.

**Comment by stevo01** [comment]
> Thanks a lot @stevo01.
> 
> > Proposal: make the php code more robust and follow redirections ...
> 
> Of course a good idea but do we realy (still) need this proxy script?
> With modern javascript we should do the request directly from the users browser and get data directly. CORS needs to be configured properly at the destination server to allow this.

I totally agree. We should not waste time with beautification of the php code ...
