### ISSUE TITLE
seamark.php - wrong usage of "starboard" and "port" site 

### ISSUE THREAD

**Issue by stevo01** [OpenSeaMap/online_chart#147]
user marco send following notification:

 https://map.openseamap.org/legend.php?lang=it&page=seamark

wrong:
> Segnale di tribordo
> Segnale di babordo
> Canale preferito: tribordo
> Canale preferito: babordo

correct:
> Segnale di dritta
> Segnale di sinistra
> Canale preferito: dritta
> Canale preferito: sinistra

**Comment by stevo01** [comment]
see 
https://en.wikipedia.org/wiki/Lateral_mark#Region_A 
vs 
https://en.wikipedia.org/wiki/Lateral_mark#Region_B

**Comment by blind-fish** [comment]
I think dritta/sinistra and tribordo/babordo are interchangable, although I found more instances of tribordo/babordo.
Image-labels (and alt-texts) seem alright for Italy, so i dont quite get the wiki-links.
Or did someone already fix this?

**Comment by stevo01** [comment]
> dritta/sinistra and tribordo/babordo are interchangable, although I found more instances of tribordo/babordo
Thanks for the comment. The link to wikipedia is just a reference document.
