### ISSUE TITLE
OpenCPN download functionality does not work

### ISSUE THREAD

**Issue by wschildbach** [OpenSeaMap/online_chart#158]
Tools->Download->OpenCPN (Kap) points to the defunct server https://downloadlayer--onlinechart-ol3.netlify.app/ .

A simple workaround would be to instead point to [alpha](http://alpha.openseamap.org/#/download/.*/2040575595?lat=27.1957&lon=-12.0683&zoom=3&layers=A00000011000&lang=en).

**Comment by wschildbach** [comment]
It looks like this is merged, bit not deployed to the production server...?

**Comment by aAXEe** [comment]
Sorry I missed the deployment part.

Now the production server uses the current state:

![image](https://user-images.githubusercontent.com/3298652/152590545-36d20917-afe9-4475-81d9-a1762a1bd762.png)
