### ISSUE TITLE
maps.openseamap.org is not available

### ISSUE THREAD

**Issue by ferrisbuhler** [OpenSeaMap/online_chart#166]
Dear makers of the OpenSeaMap
Most probably you already got aware of the fact that the full web view of the openseamap (https://maps.openseamap.org/) is currently not accessible. The error message says that the "Let's encrypt" SSL certificate is expired since 26.10.2022.
Thanks for providing this great service! Good luck!

**Comment by wschildbach** [comment]
After hardware repairs, some machines did not come back up. This should now be fixed again.
