### ISSUE TITLE
Distance scale in map legend incorrect

### ISSUE THREAD

**Issue by dfa** [OpenSeaMap/online_chart#17]
###### Affected browser versions
- Seems to be a browser independent problem.
###### Description

The distance scale in the bottom left of the on-line map is incorrect at latitudes other than the equator.
###### How to reproduce the problem
- Move to another latitude than the equator
###### Expected result
- The distance scale should display the correct distances.
#### Migrated from SourceForge

ID: 3587874
Submitted: Malcolm - 2012-11-16 04:03:29 PST
Details:

The distance scale in the bottom left of the on-line map is incorrect at latitudes other than the equator.

**Comment by ehrenfeu** [comment]
This issue will be fixed with OL3.

**Comment by wschildbach** [comment]
> Ich würde in Zeile 123 (new OpenLayers.Control.ScaleLine) einfach ein `geodesic: true` hinzufügen. Also:
> 
> ```js
> new OpenLayers.Control.ScaleLine({topOutUnits : "nmi", bottomOutUnits: "km", topInUnits: 'nmi', bottomInUnits: 'km', maxWidth: '40', geodesic: true}),
> ```
> 
> Dann wird der Maßstabsleiste entsprechend der geographischen Breite berechnet und ändert sich, wenn man vom Äquator zu den Polen wechselt. Projektionsbedingt gilt die angegebene Strecke natürlich nur in der Horizontalen.

OL3 and up do not seem to have (or need) this property anymore, but it is good to have a reference to the source of the problem.
