### ISSUE TITLE
Tiles server Down

### ISSUE THREAD

**Issue by francescobianca** [OpenSeaMap/online_chart#175]
Hi,

we are encountering problems reaching the openseamap tiles server (https://tiles.openseamap.org/); Is the system under maintenance?

**Comment by Nautic** [comment]
Thanks for your error message. We are working on...
What is your use case?

**Comment by francescobianca** [comment]
Now it's back to working! Thanks for the support. I use the tiles server as an additional layer on mapbox. I take the opportunity to ask if there is a docker image for the tiles server (https://tiles.openseamap.org/seamark)

**Comment by stevo01** [comment]
seems to be solved ...
