### ISSUE TITLE
Blue overlay on activated AIS layer

### ISSUE THREAD

**Issue by dfa** [OpenSeaMap/online_chart#19]
###### Affected browser versions
* (unknown)

###### Description
When the AIS layer is activated, a blue overlay will occur from time to time, when moving the map.

###### How to reproduce the problem
* (unknown)

###### Expected result
* No blue overlay when moving the map.

#### Migrated from SourceForge

ID: 3560007
Submitted: Markus - 2012-08-20 17:26:59 PDT
Details:

Beim Verschieben der Karte bei angezeigtem AIS-Layer wird manchmal die ganze Karte (das Browserfenster) mit blauer Farbe überzogen. Was dazu führt kann ich nicht erkennen.

**Comment by ehrenfeu** [comment]
I've never seen this behaviour. As no one else complained for this long period, I'll close the issue.

Feel free to re-open it in case we receive additional information / reports!
