### ISSUE TITLE
Trip planner - wrong results crossing 180°

### ISSUE THREAD

**Issue by dfa** [OpenSeaMap/online_chart#20]
###### Affected browser versions
* Seems to be a browser independent problem.

###### Description
When crossing the 180° meridian W>E or E>W on the trip planner, the calculated distance is wrong and the line will not be drawn correctly.

###### How to reproduce the problem
* Activate the trip planner
* Draw a trip across the date line

###### Expected result
* Correct line drawing.
* Correct distance calculation.

#### Migrated from SourceForge

ID: 3602866
Submitted: Markus - 2013-01-31 11:53:07 PST
Details:

If we cross the 180° meridian W>E or E>W the calculated distance is wrong also the drawn line is wrong

**Comment by ehrenfeu** [comment]
This is fixed with the trip planner in the OL3 map.
