### ISSUE TITLE
Trip planner 

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#28]
Affected browser versions

    FF, may be others?

Description

    When drawing a route,, the final double click delete the line on the map,
    This makes the trip planner unusable.

How to reproduce the problem

    Activate the trip planner
    Draw a trip 
    Close the route by double click

Expected result

    Correct line drawing.

**Comment by ehrenfeu** [comment]
For me this works without any problems. Tested with:

* FF 34 (Linux)
* Chrome 39 (Linux)
* IE 9 (Win7)

I'm therefore closing this bug.
