### ISSUE TITLE
Menu > Tools > Permalinks - bug when description field is empty

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#39]
If the chart was opened using a permalink, the tool "Permalink" is no more usable (does not open).

**Comment by ehrenfeu** [comment]
This is working fine for me with the current map. Can you please test again?

**Comment by ehrenfeu** [comment]
I think this is solved. Feel free to re-open the issue with more details in case the problem persists!

**Comment by Nautic** [comment]
Das Verhalten ist nach wie vor fehlerhaft:
Klick auf "Permalink" öffnet wie erwartet die aktuelle Kartenansicht und zeigt die URL in der Adresszeile.
Anschliessend ist es aber nicht möglich, im Menü "Werkzeuge" das Tool "Permanlink" zu öffnen.
Zwar kann man den Haken setzen, aber das hat keine Wirkung.

Generell wäre es sinnvoll, einen Menüeintrag durch Anklicken /irgendwo/ in der Zeile öffnen zu können.
Bis jetzt geht das nur, wenn man /genau/ das Häkchen-Viereck trifft (bei Touchscreens schwierig).

**Comment by ehrenfeu** [comment]
Ah, now I can reproduce this, it's about the "Marker Permalink" function in the "Tools" menu! Thanks for the additional information.

Apparently there is a problem with the "marker text" - if you open the map using a marker-permalink the menu function doesn't work any more if the marker doesn't have a description.

If the marker **does** have a description, it is working fine.

**Comment by Nautic** [comment]
Im Menü "Werkzeuge" Tool "Permalink" gibt es noch zwei weitere Fehler:

1. Wenn ein Marker gesetzt wird, kann dieser durch einen zweiten Klick geändert werden.
   Wenn ein Text eingetragen wird, kann der beliebig geändert werden.
   Wen aber die Layer geändert werden, wird die Änderung nicht in die URL übernommen.
2. Im Originalcode gab es einen Knopf für "fett". Damit konnte man markierte Textteile fett machen.
   Dieser Button fehlt heute. Stattdessen muss man händisch HTML einfügen (<b></b>).

**Comment by ehrenfeu** [comment]
1. I can confirm this, the layers only get updated when the marker is re-positioned with another click.

**Comment by aAXEe** [comment]
I fixed the errors described here in #70 
The formating helper (bold etc.) is a new feature from my point of view. Currently html is supported but I am not sure whether this is a good idea for security reasons (see http://stackoverflow.com/questions/33184716/is-it-save-to-display-html-code-decoded-by-decodeuricomponent-from-a-url)

**Comment by aAXEe** [comment]
I removed the html markup option now (https://github.com/aAXEe/online_chart/commit/8649157158f921590d650e2d2f4bdf0df1017e9d). It is unsafe.
I think it is better to not have formating than exposing our visitors a XSS vulnerability.

**Comment by Nautic** [comment]
Sicherheit geht vor.

Aber kann man nicht wenigstens begrenzt HTML erlauben?
fett, neue Zeile...

Viele benutzen dies für "schöne" Marker-Texte:
- Firmenname fett
- Adresse normal
- Weblink (klickbar - m.W. noch nicht realisiert)

**Comment by aAXEe** [comment]
Linebreaks (\n) are convertet in <br/> tags. All other code is displayed as plain text.

If you have a good library to parse the html and to remove all dangerous markup we could integrate that. Another option is to use something like markdown (libs: https://github.com/showdownjs/showdown or https://github.com/evilstreak/markdown-js)

**Comment by Nautic** [comment]
Markdown find' ich gut:

**Firma**
Anschrift
[Website](http://github.com)

**Comment by aAXEe** [comment]
As written above the issue from the top is solved with #70.

Adding a new markup is a new feature to be discussed here: #71

**Comment by wschildbach** [comment]
Can this issue be closed? From the comments, it seems the original bug is fixed.

**Comment by aAXEe** [comment]
Agreed
