### ISSUE TITLE
Tool Permalink (layout)

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#42]
In the code, there is a possibility for: 
- setting the first text line or some words into "bold"
- splitting the text into more than one line (4)

This is very useful for writing an adress in the permalink-popup.

This does not work until now.

**Comment by ehrenfeu** [comment]
I really don't get what this ticket / issue is about. Can you please explain more details:

* what is the current state
* what is the desired state in you suggestion?

**Comment by ehrenfeu** [comment]
No feedback yet, therefore removing it from the milestone "Boot 2015".

**Comment by aAXEe** [comment]
As far as I see all the points work in the current page.
Example: http://map.openseamap.org/map/?zoom=15&mlat=53.61835&mlon=11.48322&mtext=%3Cb%3EEin%20einsames%20Haus%3C%2Fb%3E%0AZiegelwerder%201%0A19063%20Schwerin&layers=BFFFFFFFFFF0FFFFFFFF

The text entered in the form was:
```html
<b>Ein einsames Haus</b>
Ziegelwerder 1
19063 Schwerin
```

----

Note you can enter even javascript into this form. However a simple script-tag does not work:

```html
<script>
 alert('Hello World!');
</script>
```
http://map.openseamap.org/map/?zoom=15&mlat=53.62053&mlon=11.46929&mtext=%3Cscript%3E%0A%20alert('Hello%20World!')%3B%0A%3C%2Fscript%3E&layers=BTFFFFFFFFF0FFFFFFFF

The code is visible in the page but is not executed. But I think there are solutions to get the javascript running and do something bad with it. Does someone know more about this? Is it safe to provide this festure in that way?

**Comment by ehrenfeu** [comment]
I don't think it is safe to have this "feature" - I'd rather call it a severe bug. @aAXEe you did some changes to this behaviour in your one-size-fits-all PR #70, no?

**Comment by aAXEe** [comment]
Yes it is dangerous and I removed this option. 
See https://github.com/OpenSeaMap/online_chart/issues/39

BTW: This and #39 moved away from their starting point and their titles are misleading now.

**Comment by ehrenfeu** [comment]
Yes, they are. As you have a better overview right now, could you just create one or more new tickets for the stuff that has been brought up later in #42 and #39? Then I can close these issues.

**Comment by aAXEe** [comment]
see #71
