### ISSUE TITLE
10m-depth-tracks-layer

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#45]
Jens did implement a new 10m-layer in 
http://testdepth.openseamap.org/#maptracks

The 10m-layer shows colours from red to green for 0-10m.
You can switch the layer behind the "+" in the right upper corner.

For users it would be very nice, to have this nice layer also 
in our fullscreen-chart :-)
So they can use our "infrastructure" (permalink, measuring tool)
similar to the 100m-layer:
http://map.openseamap.org/?zoom=15&lat=1.39399&lon=103.94614&layers=BFTFFFTFFTF0FFFFFTFF

See this user-request:
http://forum.openseamap.org/viewtopic.php?pid=2589#p2589

It would be great to use this feature next week 
for the visitors of "boot" :-)

Im Menü "Ansicht":

alt:
Wassertiefen (beta)
neu: Wassertiefen

neu: 2-stufiges Menü:
- Wassertiefen
-- Meeresprofil (der GEBCO-Layer)
-- 10-m-Tracks
-- 100-m-Tracks
-- Wassertiefen erfassen (Link zu depth.openseamap.org)

alt: Meeresprofil
wird ersetzt durch den neuen Unterpunkt "Meeresprofil"

alt: Entwicklung
wird ersetzt durch den neuen Unterpunkt "Wassertiefen erfassen"

**Comment by aAXEe** [comment]
I added the options for 10m and 100m trackpoints in #70 (Commit: https://github.com/aAXEe/online_chart/commit/03af5c29bda3c85052b07084c16550e108f2e7db)
You can see a preview at http://dev-map.brasshack.de/

**Comment by aAXEe** [comment]
https://github.com/aAXEe/online_chart/commit/8649157158f921590d650e2d2f4bdf0df1017e9d adds the contour layer
