### ISSUE TITLE
Törnplaner - Daten speichern und laden

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#46]
Beim Törnplaner gibt es die Möglichkeit, den gezeichneten Track zu speichern.

Bei der Speicherung als CSV geht der Startpunkt verloren (wird nicht gespeichert).
Gespeichert werden die Wegsegmente, mit Kurs, Distanz und Position des Wegpunktes.
Dabei enthalten die Einträge aber zusätzliche/falsche Zeichen: Â in Excel, " in note++.
Beispiel s. https://sourceforge.net/p/openseamap/bugs/59/

Sinnvoll wäre auch die Möglichkeit, einen gespeicherten Track zur Anzeige
bzw. zur weiteren Bearbeitung wieder einzulesen.
Dann könnte man sich auch Tracks per Mail zusenden.

Wenn man beim Track-Bearbeiten zufällig/irrtümlich irgendwo ins Leere klickt (beispielsweise beim Verschieben der Karte) ändert der Track die Farbe von rot auf blau und ist nicht mehr bearbeitbar. Ich habe keine Möglichkeit gefunden, den "Bearbeiten"-Zustand wieder herzustellen. Man muss dann wieder von vorne anfangen.
Vielleicht kann man noch einen "Edit"-Button einbauen?

Gut wäre auch eine 3. Nachkommastelle,
damit man den Törnplaner als genaues Messinstrument verwenden kann.
Vielleicht muss man das selektiv machen, nur für kurze Distanzen? (z=15..18)
Beim Kurs wäre m.E. eine Nachkommastelle ausreichend.

Von OSMern kam die Bitte, dass hilfreich wäre,
wenn man von Seemeilen auf km umschalten könnte.

Ein weiterer Wunsch war: GPX als Ausgabeformat

- - - -

Short translation:

Tracks can be stored - but no more imported...
So on can not edit tracks later...
And on can not view the track...

3 digits after comma would be useful.
Option: nm/km wold be useful.
GPX as format.

**Comment by ehrenfeu** [comment]
Bitte keine "Sammeltickets" anlegen, das wird schnell extrem unübersichtlich. Falls doch, dann nur um andere Tickets zu referenzieren, die ganzen einzelnen Punkte sollten auch in separaten Issues angelegt werden. Ich habe das jetzt gemacht und werde daher dieses Über-Ticket schliessen.

Please don't create [Über-tickets](http://en.wikipedia.org/wiki/%C3%9Cber), as it is very hard this way to keep track of the individual tasks. If absolutely necessary, then please only use them as meta-issues to collect references to other tickets, containing the individual descriptions. This is done now, therefore I'm closing this issue.
