### ISSUE TITLE
Download Layer

### ISSUE THREAD

**Issue by Dirk--** [OpenSeaMap/online_chart#54]
Download layer points to http://sourceforge.net/projects/opennautical/files/Maps/Region/
Most of these files are outdated!
I would suggest to disable this layer (at least display a note).

**Comment by ehrenfeu** [comment]
Agreed. I guess the download files are (were?) generated by Olaf, can we put this process on one of the OSeaM machines? From my understanding, OpenNautical is a project purely driven by Olaf...?

**Comment by Dirk--** [comment]
Activity: http://sourceforge.net/p/opennautical/activity/?page=0&limit=100
As far as I know:
al_friede=olaf, leo12305=rolf
Alexej is working on rebirth: https://github.com/OpenSeaMap/chart-designer

**Comment by wschildbach** [comment]
The layer is disabled in the code, so this issue can be closed.
