### ISSUE TITLE
Compass rose

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#86]
Ein Benutzer wünscht sich ein Tool "Kompassrose".

Die Rose soll eine feine Gradeinteilung und einen Mittelpunkt haben,
um damit rechtweisende Kurse ablesen zu können.
Die Rose soll auf der Karte per Maus verschiebar sein,
und über "Werkzeuge" ein- und ausschaltbar.

**Comment by wschildbach** [comment]
@Nautic Das issue können wir dann wohl zumachen.

**Comment by wschildbach** [comment]
We have a compass rose now; and it can be used to read off courses.
