### ISSUE TITLE
Permalink for Marine traffic : this layer should be refreshed

### ISSUE THREAD

**Issue by pyrog** [OpenSeaMap/online_chart#92]
Similar as #91 but also the **marine traffic** is never displayed (just the logo).

Affected browser versions
* Seems to be a browser independent problem.

Description
* When creating a permalink with activated **Marine traffic**, this layer is not displayed until this layer is checked/unchecked.
* In all cases, the traffic itself is never displayed (only this logo below)<br/>
<img width="86" alt="logo" src="https://cloud.githubusercontent.com/assets/2158081/15826633/a2bc82f2-2c08-11e6-871b-f95c07580c1e.png">

How to reproduce the problem
* Activate the **Marine traffic** layer
* Create permalink
* [Follow it](http://map.openseamap.org/?layers=BFFFFFFFFFF0TFFFFFFFFF&zoom=8&lat=49.86934&lon=-4.07905)

Expected result
* The map should be loaded and display the **Marine traffic** layer.
<img width="597" alt="good" src="https://cloud.githubusercontent.com/assets/2158081/15826744/11cecd26-2c09-11e6-8c69-4248f1843008.png">

Result
* The checkbox is still checked but the logo and the traffic are not displayed.
<img width="597" alt="bad" src="https://cloud.githubusercontent.com/assets/2158081/15826750/178f3868-2c09-11e6-859e-28753f3e008f.png">

**Comment by aAXEe** [comment]
Sorry for this:

Actually we do not have a working marine traffic backend. So you can activate the layer but it will never show any data. See also http://forum.openseamap.org/viewtopic.php?id=2188
We are in active communication with marine traffic to get a working api again.

**Comment by pyrog** [comment]
> Actually we do not have a working marine traffic backend.

Ok, thanks for that part of the issue 😄 
Could you just display a warning message until the API work again ?

But this issue should be still opened for permalink that not refresh this (empty) layer 😉 
(the logo should appear after a click on the permalink)
